### ISSUE TITLE
Can we connect? :)

### ISSUE THREAD

**Issue by Tolli** [voi-oss/dbt-exposures-crawler#11]
Hi, I've been looking at your repository and I'm wondering whether you are available for some ad-hoc mentoring, i.e. guiding me on creating a custom adapter for dbt from scratch. Please contact me @ tolli at quicklookup.com if you are interested in a discussion or something more :)

Wishing you an awesome day,

Cheers,
Tolli.

**Comment by fernandobrito** [comment]
Hi, @Tolli. This is unfortunately not something we can provide, but you could try reaching out to the dbt community on Slack: https://www.getdbt.com/community/join-the-community.
